version: "3"

x-common: &common
  working_dir: /go/src/microservice
  tty: true
  expose:
      - 8080
  command: bash -c "go run main.go"

services:
  nginx-proxy:
    image: jwilder/nginx-proxy:alpine
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./conf:/etc/nginx/vhost.d
    depends_on:
      - service-a
      - service-b
      - service-c

  termination:
    image: containous/whoami
    environment:
      - VIRTUAL_HOST=localhost

  service-a:
    <<: *common
    build:
      context: "./service-a"
    volumes:
      - ./service-a:/go/src/microservice

  service-b:
    <<: *common
    build:
      context: "./service-b"
    volumes:
      - ./service-b:/go/src/microservice

  service-c:
    <<: *common
    build:
      context: "./service-c"
    volumes:
      - ./service-c:/go/src/microservice
